// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzxyxnfkuxwtcutbxtcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16eHl4bmZrdXh3dGN1dGJ4dGNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTU0MjcsImV4cCI6MjA2NDUzMTQyN30.D4TOSYLaUYOsnVZMsyUwYt8elKpw1_GqCgUAMNsKclU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);